version: '3.7'

services:
  spark-worker-3:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.8.161:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "38083:8081"
    volumes:
      - ./app:/app
    working_dir: /app
    user: root
    networks:
      - lakehouse

  spark-worker-4:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.8.161:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "38084:8081"
    volumes:
      - ./app:/app
    working_dir: /app
    user: root
    networks:
      - lakehouse

networks:
  lakehouse:
    driver: bridge
